# Generated by Django 3.2.8 on 2024-06-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('genre', models.CharField(max_length=50, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('release_date', models.DateField(verbose_name='Fecha de Lanzamiento')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.artists', verbose_name='Artista')),
            ],
        ),
    ]
